version: "3.9"

services:
  mongo:
    container_name: mongo
    image: mongo:${MONGO_VERSION} # https://hub.docker.com/_/mongo
    entrypoint:
      - bash
      - -c
      - |
        if [ ! -f ${MONGO_REPLICA_SET_KEY_FILE} ]; then
          echo "generating replica set key file ..."
          openssl rand -base64 756 > ${MONGO_REPLICA_SET_KEY_FILE}
          chmod 600 ${MONGO_REPLICA_SET_KEY_FILE}
          chown 999:999 ${MONGO_REPLICA_SET_KEY_FILE}
        fi
        exec docker-entrypoint.sh $$@
    command: "--bind_ip_all --replSet ${MONGO_REPLICA_SET_NAME} --keyFile ${MONGO_REPLICA_SET_KEY_FILE}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: >
        mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --eval "try { rs.status().ok } catch (e) { rs.initiate({ _id: '${MONGO_REPLICA_SET_NAME}', members: [{ _id: 0, host: 'localhost:27017' }] }).ok }"
      timeout: 15s
      start_period: 15s
      retries: 10
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mongo-network

volumes:
  mongo_data:
  mongo_config:

networks:
  mongo-network:
